(define (problem manip-generated)
  (:domain manip-tamp)

  (:objects
    banana_0 coke_can_0 hammer_0 hammer_1 hammer_2 meat_can_0 meat_can_1 - item
    left_storage right_storage bookshelf buffer1 buffer2 - location
  )

  (:init
    (at banana_0 table)
    (at coke_can_0 table)
    (at hammer_0 table)
    (at hammer_1 table)
    (at hammer_2 table)
    (at meat_can_0 table)
    (at meat_can_1 table)
    (blocks hammer_0 coke_can_0)
    (blocks hammer_0 hammer_1)
    (blocks hammer_0 hammer_2)
    (blocks hammer_0 meat_can_0)
    (blocks hammer_0 meat_can_1)
    (blocks hammer_1 hammer_2)
    (blocks meat_can_1 hammer_1)
    (blocks meat_can_1 hammer_2)
    (buffer buffer1)
    (buffer buffer2)
    (buffer-free buffer1)
    (buffer-free buffer2)
    (clear banana_0)
    (clear hammer_0)
    (goal-at banana_0 left_storage)
    (goal-at coke_can_0 bookshelf)
    (goal-at hammer_0 right_storage)
    (goal-at meat_can_0 left_storage)
    (graspable banana_0)
    (graspable coke_can_0)
    (graspable hammer_0)
    (graspable hammer_1)
    (graspable hammer_2)
    (graspable meat_can_0)
    (graspable meat_can_1)
    (handempty)
    (near coke_can_0 hammer_0)
    (near coke_can_0 hammer_1)
    (near coke_can_0 meat_can_1)
    (near hammer_0 coke_can_0)
    (near hammer_0 hammer_1)
    (near hammer_0 meat_can_1)
    (near hammer_1 coke_can_0)
    (near hammer_1 hammer_0)
    (near hammer_1 meat_can_1)
    (near meat_can_1 coke_can_0)
    (near meat_can_1 hammer_0)
    (near meat_can_1 hammer_1)
    (safe banana_0)
    (safe coke_can_0)
    (safe hammer_0)
    (safe hammer_1)
    (safe hammer_2)
    (safe meat_can_0)
    (safe meat_can_1)
    (storage bookshelf)
    (storage left_storage)
    (storage right_storage)
    (target banana_0)
    (target coke_can_0)
    (target hammer_0)
    (target hammer_1)
    (target hammer_2)
    (target meat_can_0)
    (target meat_can_1)
  )

  (:goal
    (and
      (at banana_0 left_storage)
      (at meat_can_0 left_storage)
      (at hammer_0 right_storage)
      (at coke_can_0 bookshelf)
    )
  )
)
